# Generated by Django 6.0.5 on 2026-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadjob",
            old_name="file_path",
            new_name="title",
        ),
        migrations.AddField(
            model_name="downloadjob",
            name="cloud_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="downloadjob",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadjob",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadjob",
            name="platform",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="downloadjob",
            name="thumbnail",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="downloadjob",
            name="uploader",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
